name: API-KIDS-R-US

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  laravel-build:
    uses: ./.github/workflows/workflow-build.yml
    secrets: inherit

  laravel-lint-code:
    needs: laravel-build
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        id: install-dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHP Pint test
        id: php-pint-test
        run: vendor/bin/pint --test

      - name: PHPSTAN CODE ANALYZE
        id: phpstan-analyze
        run: vendor/bin/phpstan analyse --memory-limit=2G --no-progress

  laravel-test:
    needs: laravel-lint-code
    uses: ./.github/workflows/workflow-build.yml
    secrets: inherit
    steps:
      - name: Running Functional and Unit Tests
        id: running-tests
        run: php artisan test -p --coverage
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
